gui:
  language: 'en'
  scrollOffMargin: 4
  nerdFontsVersion: '3'
  spinner:
    frames:
      - '󰪞'
      - '󰪟'
      - '󰪠'
      - '󰪡'
      - '󰪢'
      - '󰪣'
      - '󰪤'
      - '󰪥'
  statusPanelView: 'allBranchesLog'
  theme:
    activeBorderColor:
      - '#a6e3a1'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#a6e3a1'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
    authorColors:
      '*': '#b4befe'
os:
  copyToClipboardCmd: 'echo -n "{{text}}" | xclip -sel clip'
confirmOnQuit: true
